### ISSUE TITLE
it dose not work

### ISSUE THREAD

**Issue by GouMingAnKang** [spacelama/R710-Fan-Control#4]
I upgrade my iDrac version to v2.85.85.85, then I found every tool dose't work
![image](https://github.com/spacelama/R710-Fan-Control/assets/24820061/5c1134bb-22cb-48f3-be80-cadbb9849ee4)

**Comment by spacelama** [comment]
I'm unable to help you with configuration of ipmitool on your macbook, but I strongly suspect you didn't notice this tool is for Dell Poweredge servers only.
