### ISSUE TITLE
Maximum demand + evil copy paste

### ISSUE THREAD

**Issue by pedracca** [spacelama/R710-Fan-Control#5]
The maximum demand cap should be 100 instead of 255, it is a percent that is later converted to hex value and sent to ipmi as is.

`
if ($demand>255) {
    $demand=255;
  }
`

Not really that important, as if your temps demand more than 100% to ipmi I suppose it uses 100% fan speed anyway (and you've already been cooking it), but still...

There is also a comment for the second "if" (for the three slope definitions) that should reflect the third slope points instead of the second ones.

line 153 reads
`# y1 = demand1 ; x1 = desired_temp1 ; y2 = demand2 ; x2 = desired_temp2`
and should be 
`# y1 = demand2 ; x1 = desired_temp2 ; y2 = demand3 ; x2 = desired_temp3`

Doesn't matter at all but was a bit confusing at first.

Other than that, I find this a great job at making the fan control a bit more "intelligent". Best I found so far. Thank you!

**Comment by spacelama** [comment]
Sorry, completely missed this bug - I'm not getting reliable notifications of new issues on my repos.

$demand isn't actually a percentage.  That code is a mess, but I've slightly clarified a comment in that push - $static_speed_high is more or less arbitrary - the initial ramps are chosen to sort of scale from an input of 0-255 and map to 0x02 to 0x12 ($static_speed_low to $static_speed_high), which is bloody loud and fast on my machines, but are allowed to continue linearly even further all the way to 255 if necessary if the temperature ramps up to 6 million degrees.
